# -*- coding: utf-8 -*-
"""YOLOv8m

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UPqwI24pH_qT4iDCx1uO3paG4ZzrNhbW

## **Clone dan install YOLOv8**
"""

#mounting google drive
from google.colab import drive
drive.mount('/content/drive')

#install package ultralytics
!pip install ultralytics -q

#import libraries YOLO
from ultralytics import YOLO

#install model YOLOv8m
model = YOLO("yolov8m.pt")

#mengatur path dataset
!touch data.yaml

"""## **Implementasi dan Evaluasi Model YOLOv8**

###**Pelatihan dan Pengujian Data dengan epoch 20**

#### Pelatihan Data
"""

#melatih data dengan epoch 20
model.train(data = "/content/data.yaml", epochs = 20, batch = 16, imgsz = 640, dfl = 0.2)

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
model = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch20/train/best.pt")
model.val(data='/content/drive/Shareddrives/Skripsi/Yolov8/data.yaml', split = 'test')

"""#### Tugas Deteksi"""

#memprediksi data dengan model
infer = YOLO("/content/runs/detect/train6/weights/best.pt")

#memprediksi dataset pengujian
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/test/images", save = True, save_txt = True)

#memprediksi data baru
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/testing", save = True, save_txt = True)

"""###**Pelatihan dan Pengujian Data dengan epoch 30**

#### Pelatihan Data
"""

#melatih data dengan epoch 30
model.train(data = "/content/data.yaml", epochs = 30, batch = 16, imgsz = 640, dfl = 0.2)

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
model = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch30/train/best.pt")
model.val(data='/content/drive/Shareddrives/Skripsi/Yolov8/data.yaml', split = 'test')

"""#### Tugas Deteksi"""

#memprediksi data dengan model
infer = YOLO("/content/runs/detect/train7/weights/best.pt")

#memprediksi dataset pengujian
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/test/images", save = True, save_txt = True)

#memprediksi data baru
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/testing", save = True, save_txt = True)

"""###**Pelatihan dan Pengujian Data dengan epoch 40**

#### Pelatihan Data
"""

#melatih data dengan epoch 40
model.train(data = "/content/data.yaml", epochs = 40, batch = 16, imgsz = 640, dfl = 0.2)

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
model = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch40/train/best.pt")
model.val(data='/content/drive/Shareddrives/Skripsi/Yolov8/data.yaml', split = 'test')

"""#### Tugas Deteksi"""

#memprediksi data dengan model
infer = YOLO("/content/runs/detect/train8/weights/best.pt")

#memprediksi dataset pengujian
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/test/images", save = True, save_txt = True)

#memprediksi data baru
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/testing", save = True, save_txt = True)

"""###**Pelatihan dan Pengujian Data dengan epoch 50**

#### Pelatihan Data
"""

#melatih data dengan epoch 50
model.train(data = "/content/data.yaml", epochs = 50, batch = 16, imgsz = 640, dfl = 0.2)

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
model = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch50/train/best.pt")
model.val(data='/content/drive/Shareddrives/Skripsi/Yolov8/data.yaml', split = 'test')

"""#### Tugas Deteksi"""

#memprediksi data dengan model
infer = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch50/train/best.pt")

#memprediksi dataset pengujian
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/test/images", save = True, save_txt = True)

#memprediksi data baru
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/testing", save = True, save_txt = True)

"""###**Pelatihan dan Pengujian Data dengan epoch 60**

#### Pelatihan Data
"""

#melatih data dengan epoch 60
model.train(data = "/content/data.yaml", epochs = 60, batch = 16, imgsz = 640, dfl = 0.2)

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
model = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/result/epoch60/train/best.pt")
model.val(data='/content/drive/Shareddrives/Skripsi/Yolov8/data.yaml', split = 'test')

"""#### Tugas Deteksi"""

#memprediksi data dengan model
infer = YOLO("/content/drive/Shareddrives/Skripsi/Yolov8/yolov8/epoch60/best.pt")

#memprediksi dataset pengujian
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/test/images", save = True, save_txt = True)

#memprediksi data baru
infer.predict("/content/drive/Shareddrives/Skripsi/Yolov8/testing", save = True, save_txt = True)

"""## **Download Hasil Implementasi dan Evaluasi YOLOv8**"""

import shutil

#zip folder
file_to = '/content/detect'
file_format = 'zip'
file_from = '/content/runs/detect/predict'
shutil.make_archive(file_to, file_format, file_from)