# -*- coding: utf-8 -*-
"""YOLOv5m

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WuB0NxKkrIPHo8gfJHqlKzCZPPYrLWFv

## **Clone dan install YOLOv5**
"""

#mounting google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#path direktori clone YOLOv5
# %cd /content/drive/Shareddrives/Skripsi/Yolov5

# Commented out IPython magic to ensure Python compatibility.
#clone dan install YOLOv5
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -r requirements.txt  # install

"""## **Implementasi dan Evaluasi Model YOLOv5**

###**Pelatihan dan Pengujian Data dengan epoch 20**

#### Pelatihan Data
"""

#melatih data dengan epoch 20
!python train.py --batch 16 --img 640 --epochs 20 --data custom_data.yaml --weights yolov5m.pt --nosave --cache

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python val.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch20/train/weights/best.pt --data custom_data.yaml --img 640 --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch20/train/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/images/test

#memprediksi data baru
!python detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 30**

#### Pelatihan Data
"""

#melatih data dengan epoch 30
!python train.py --batch 16 --img 640 --epochs 30 --data custom_data.yaml --weights yolov5m.pt --nosave --cache

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python val.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch30/train/weights/last.pt --data custom_data.yaml --img 640 --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch30/train/weights/last.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/images/test

#memprediksi data baru
!python detect.py --weights runs/train/exp3/weights/last.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 40**

#### Pelatihan Data
"""

#melatih data dengan epoch 40
!python train.py --batch 16 --img 640 --epochs 40 --data custom_data.yaml --weights yolov5m.pt --nosave --cache

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python val.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch40/train/weights/best.pt --data custom_data.yaml --img 640 --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch40/train/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/images/test

#memprediksi data baru
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 50**

#### Pelatihan Data
"""

#melatih data dengan epoch 50
!python train.py --batch 16 --img 640 --epochs 50 --data custom_data.yaml --weights yolov5m.pt --nosave --cache

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python val.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch50/train/weights/best.pt --data custom_data.yaml --img 640 --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch50/train/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/images/test

#memprediksi data baru
!python detect.py --weights runs/train/exp5/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 60**

#### Pelatihan Data
"""

#melatih data dengan epoch 60
!python train.py --batch 16 --img 640 --epochs 60 --data custom_data.yaml --weights yolov5m.pt --nosave --cache

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python val.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch60/train/weights/best.pt --data custom_data.yaml --img 640 --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights /content/drive/Shareddrives/Skripsi/Yolov5/result/epoch60/train/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/images/test

#memprediksi data baru
!python detect.py --weights runs/train/exp2/weights/best.pt --img 640 --conf 0.25 --source /content/drive/Shareddrives/Skripsi/Yolov5/testing