# -*- coding: utf-8 -*-
"""YOLOv7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KMHWityuThTTntHKhl3fVp2OpN9__3x4

## **Clone dan install YOLOv7**
"""

#mounting google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#path direktori clone YOLOv7
# %cd /content/drive/Shareddrives/Skripsi/Yolov7

#clone YOLOv7
!git clone https://github.com/WongKinYiu/yolov7

#clone model yolov7
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

"""## **Implementasi dan Evaluasi Model YOLOv7**

###**Pelatihan dan Pengujian Data dengan epoch 20**

#### Pelatihan Data
"""

#melatih data dengan epoch 20
!python train.py --batch-size 16 --img 640 640 --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --epochs 20 --data data/custom_data.yaml --weights yolov7.pt --name yolov7-custom

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python test.py --data data/custom_data.yaml --img 640 --device 0 --weights runs/train/yolov7-custom/weights/best.pt --name yolov7_640_test --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights runs/train/yolov7-custom/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/test/images

#memprediksi data baru
!python detect.py --weights runs/train/yolov7-custom/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 30**

#### Pelatihan Data
"""

#melatih data dengan epoch 30
!python train.py --batch-size 16 --img 640 640 --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --epochs 30 --data data/custom_data.yaml --weights yolov7.pt --name yolov7-custom

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python test.py --data data/custom_data.yaml --img 640 --device 0 --weights runs/train/yolov7-custom2/weights/best.pt --name yolov7_640_test --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights runs/train/yolov7-custom2/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/test/images

#memprediksi data baru
!python detect.py --weights runs/train/yolov7-custom2/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 40**

#### Pelatihan Data
"""

#melatih data dengan epoch 40
!python train.py --batch-size 16 --img 640 640 --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --epochs 40 --data data/custom_data.yaml --weights yolov7.pt --name yolov7-custom

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python test.py --data data/custom_data.yaml --img 640 --device 0 --weights runs/train/yolov7-custom3/weights/best.pt --name yolov7_640_test --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights runs/train/yolov7-custom3/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/test/images

#memprediksi data baru
!python detect.py --weights runs/train/yolov7-custom3/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 50**

#### Pelatihan Data
"""

#melatih data dengan epoch 50
!python train.py --batch-size 16 --img 640 640 --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --epochs 50 --data data/custom_data.yaml --weights yolov7.pt --name yolov7-custom

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python test.py --data data/custom_data.yaml --img 640 --device 0 --weights runs/train/yolov7-custom5/weights/best.pt --name yolov7_640_test --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights runs/train/yolov7-custom5/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/test/images

#memprediksi data baru
!python detect.py --weights runs/train/yolov7-custom5/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/testing

"""###**Pelatihan dan Pengujian Data dengan epoch 60**

#### Pelatihan Data
"""

#melatih data dengan epoch 60
!python train.py --batch-size 16 --img 640 640 --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/yolov7-custom.yaml --epochs 60 --data data/custom_data.yaml --weights yolov7.pt --name yolov7-custom

"""#### Pengujian Data"""

#menguji model dengan dataset pengujian
!python test.py --data data/custom_data.yaml --img 640 --device 0 --weights runs/train/yolov7-custom6/weights/best.pt --name yolov7_640_test --task test

"""#### Tugas Deteksi"""

#memprediksi dataset pengujian
!python detect.py --weights runs/train/yolov7-custom6/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/test/images

#memprediksi data baru
!python detect.py --weights runs/train/yolov7-custom6/weights/best.pt --img-size 640 --source /content/drive/Shareddrives/Skripsi/Yolov7/testing